<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EriReborn.SampleExtension</RootNamespace>
    <AssemblyName>EriReborn.SampleExtension</AssemblyName>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EriReborn.Extension\EriReborn.Extension.csproj" />
  </ItemGroup>
</Project>
