<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EriReborn.Asset</RootNamespace>
    <AssemblyName>EriReborn.Asset</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EriReborn.Core\EriReborn.Core.csproj" />
  </ItemGroup>
</Project>
