namespace EriReborn.Core.Catalog;

/// <summary>A public key the build itself trusts to sign catalog data.</summary>
public sealed record CatalogTrustKey(string KeyId, string Algorithm, string PublicKey, string? Publisher);

/// <summary>
/// The pinned root of trust for official catalog data.
///
/// This list is compiled into the assembly on purpose. The catalog's own
/// <c>keys.json</c> lives next to the data it would protect, so an attacker who
/// can replace the catalog can replace that file too. A trust root that travels
/// with the thing it authenticates authenticates nothing.
///
/// Several keys may be listed to allow rotation: publish the next public key in
/// an application update, re-sign with the new private key, then drop the old
/// entry in a later update.
/// </summary>
public static class CatalogTrustAnchor
{
    public const string DefaultAlgorithm = "ecdsa-p256-sha256";

    /// <remarks>
    /// Wrapped, not handed out as the array it is built from: an <c>IReadOnlyList</c> over an array can
    /// be cast back to that array and written to, which would let anything in the process put its own key
    /// into the root of trust and make every signature checked against this list decorative.
    /// </remarks>
    public static IReadOnlyList<CatalogTrustKey> Keys { get; } = Array.AsReadOnly(new[]
    {
        // Generated by `Smoke -- --gencatalogkey`. The private half lives only in
        // the maintainer's user data directory and is never shipped or committed.
        new CatalogTrustKey(
            "erireborn-catalog-2026",
            DefaultAlgorithm,
            "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKasd5LN4eIqErL26Nxmh6wRQlHhYq6b9WtKkjOf3o3BKvo3/4cJMtQXwzMKuymWiN+fALzJOuh1VtwJ5lBS8Cw==",
            "EriReborn"),
    });

    public static CatalogTrustKey? Find(string keyId)
        => Keys.FirstOrDefault(k => string.Equals(k.KeyId, keyId, StringComparison.Ordinal));
}
